name: air_quality_feature_pipeline_us

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *' # every day at 05:30

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          
      - name: install python packages
        run:
          pip install -r requirements.txt
          
      - name: execute Feature Pipeline
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          CONTINENT: "US"
        run: python ./feature_pipeline.py